"""Generate Go allocation DTOs mechanically from the authoritative Pydantic models."""
from typing import Annotated, Literal, get_args, get_origin
from resume_contracts import models


def go_type(annotation):
    origin, args = get_origin(annotation), get_args(annotation)
    if origin is Annotated: return go_type(args[0])
    if origin is Literal: return go_type(type(args[0]))
    if origin is list: return '[]' + go_type(args[0])
    if annotation in (str, bool, int): return {str:'string', bool:'bool', int:'int64'}[annotation]
    return annotation.__name__


def generate():
    lines=['// Code generated by resume-contracts tools/build_bundle.py. DO NOT EDIT.', 'package contract', '']
    for name, cls in vars(models).items():
        if not name.startswith('Allocation') or not isinstance(cls,type) or not issubclass(cls,models.StrictModel): continue
        lines.append('type '+name+' struct {')
        for field, info in cls.model_fields.items():
            label=''.join({'id':'ID','ids':'IDs','bps':'BPS','ms':'MS'}.get(p,p.title()) for p in field.split('_'))
            lines.append(f'\t{label} {go_type(info.annotation)} `json:"{field}"`')
        lines.extend(['}', ''])
    return ('\n'.join(lines)+'\n').encode()
